name: Build Zebra

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        rootless: [0, 1]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.rootless }}
      cancel-in-progress: true

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies
      run: brew install ldid make

    - name: Setup Theos
      uses: actions/checkout@v2
      with:
        repository: theos/theos
        path: theos
        submodules: recursive

    - name: Build Package
      env:
        THEOS: theos
      run: gmake package ROOTLESS=${{ matrix.rootless }}
